### PR TITLE
fix: force unix line endings in build

### LINKED ISSUE #78: Bug: /usr/bin/env: ‘node\r’: No such file or directory
After the installation, I try to run docsify. However, there's an error saying `/usr/bin/env: ‘node\r’: No such file or directory`.
Finally, I found the solution to the problem.
Just to use `dos2unix` to convert `/use/local/lib/node_modules/docsify-cli/bin/docsify` to Unix format.
Maybe it is the format(dos) of the file that cause the problem.

### PR DESCRIPTION
**Pull request by sapkra**
Can you please check if this fixes the wrong line endings in the build/bin?
I think the problem is only occurring when the binary is built on windows (I don't have a windows system ready right now).

Fixes #78

### CODE REVIEW

**Comment by anikethsaha** [comment]
thanks a lot for the PR 💯 

it looks like that plugin is still using really old version of rollup `0.50.0` and rollup is in `2.x`, and we are using `1.27` and that plugin's last commit was Jan 19. 
So I am not sure how much that is compatible with rollup's API.  is there any similar plugin ?
or otherwise, we or (someone) need to fork it and release it. 

WDYT ?

**Comment by sapkra** [comment]
The plugin should work on all OS's. It will just force the line endings to be unix line endings (it's the default). Another solution would be to build docsify on a unix machine or using WSL on Windows.
In this case the line endings of the build would automatically have the correct line endings.

**Comment by anikethsaha** [comment]
@sapkra is the plugin compatible with the rollup `1.x` ?

**Comment by sapkra** [comment]
I tried to convert the line endings to windows line endings using this plugin on my mac and it was working fine. But please test it yourself. I will not put any afford into this PR anymore because I've switched to docusaurus.

Many others in your community still have this problem. So please think about the solutions like using a CI like Github Actions, using WSL or Docker to build it or using this plugin on windows. The plugin is the worst solution in my opinion.

**Comment by anikethsaha** [comment]
thanks for the info.

**Pull request closed without merging**
