### PR TITLE
fix: npm audit issues

### PR DESCRIPTION
**Pull request by L2jLiga**

### CODE REVIEW

**Comment by L2jLiga** [comment]
@QingWei-Li can you take a look?

**Comment by L2jLiga** [comment]
*branch*: master
*command*: `npm ci && npm audit`
*result*:
```
found 15 vulnerabilities (3 low, 2 moderate, 10 high) in 1689 scanned packages
  run `npm audit fix` to fix 11 of them.
  4 vulnerabilities require manual review. See the full report for details.
```

this PR: 
```
found 4 vulnerabilities (2 low, 2 moderate) in 2736 scanned packages
  4 vulnerabilities require manual review. See the full report for details.
```

all PR vulnerabilities found in `docsify` and `docsify-server-renderer`

**Comment by anikethsaha** [comment]
Thanks for that detailed comment. 
I will take a look soon. 
I guess  we need to update some packages in the main repo as well.

**Comment by L2jLiga** [comment]
PR for updating packages in main repo already in master: https://github.com/docsifyjs/docsify/pull/934

**Comment by anikethsaha** [comment]
Released https://www.npmjs.com/package/docsify-cli/v/4.4.0 👍

**Pull request merged**
