### PR TITLE
chore: post release cleanup

### PR DESCRIPTION
**Pull request by sy-records**
Test files are not auto updated when a release is released...

### CODE REVIEW

**Review by jamesgeorge007 — COMMENTED** [review]
Add the following to `package.json`:-

```json
"standard-version": {
    "scripts": {
      "prerelease": "ava e2e/cli.test.js -u"
    }
  },
```

**Comment by sy-records** [comment]
This is not what I was expecting... 

Ava needs to be executed here to update the screenshot, otherwise it is still the old version.

image

If it's not supported, it has to be done manually 🤣

**Comment by jamesgeorge007** [comment]
It seems the `postbump` lifecycle script would do the job.

```diff
-    "release": "standard-version"
+    "release": "standard-version -a"
+  },
+  "standard-version": {
+    "scripts": {
+      "postbump": "ava e2e/cli.test.js -u && git add ."
+     }
+  },
```

**Comment by sy-records** [comment]
Thanks, you're right! 👍🏻

**Review by jamesgeorge007 — APPROVED** [review]

**Pull request merged**
